spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your mail
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

elasticsearch-url: ${ES_URL:127.0.0.1:9200}